- src: https://github.com/open-io/ansible-role-openio-gridinit.git
  version: master
  name: gridinit

- src: https://github.com/racciari/ansible-role-repo-openio-sds
  version: master
  name: repo

- src: https://github.com/mjanser/ansible-role-mysql.git
  version: master
  name: mysql

