# Test playbook
---
- name: generate docker keystone group
  hosts: all
  gather_facts: false
  tasks:
    - add_host:
        name: localhost
        groups: keystone
      delegate_to: localhost
      run_once: true
      changed_when: false

- hosts: localhost
  become: true
  roles:
    - role: repo
    - role: gridinit
    - role: role_under_test
      openio_keystone_wsgi_processes: 2
      openio_keystone_config_cache_memcache_servers: ""
      openio_keystone_nodes_group: keystone
...
