---
- include: keystone_credentials_keys_create.yml
  when: inventory_hostname == groups['keystone_all'][0]

- name: Copying credentials key repository
  synchronize:
    mode: push
    src: "{{ keystone_credentials_tokens_key_repository }}"
    dest: "{{ keystone_credentials_tokens_key_repository }}"
  when: inventory_hostname != groups[openio_keystone_inventory_group][0]
  delegate_to: groups[openio_keystone_inventory_group][0]
...
