---
- include: keystone_fernet_keys_create.yml
  when: inventory_hostname == groups[openio_keystone_inventory_group][0]

- name: Copying fernet key repository
  synchronize:
    mode: push
    src: "{{ openio_keystone_fernet_tokens_key_repository }}"
    dest: "{{ openio_keystone_fernet_tokens_key_repository }}"
  when: inventory_hostname != groups[openio_keystone_inventory_group][0]
  delegate_to: "{{ groups[openio_keystone_inventory_group][0] }}"
...
