---
# handlers file for ansible-role-openio-keystone

- name: Restart uWGSI
  service:
    name: "openstack-keystone-admin"
    enabled: yes
    state: restarted
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary('yes', omit) }}"
  register: _restart
  until: _restart | success
  retries: 5
  delay: 2
